In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from datasets import load_dataset
import ast

dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [ ]:
# Filter out rows with NaN values in the 'salary_year_avg' column
df_salary = df[pd.notna(df['salary_year_avg'])].copy()

### Apply calculation onto a column using function

In [28]:
def projected_salary(salary):
    return salary * 1.03

In [31]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)

df_salary.head(2)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,salary_year_inflated
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"[gdpr, excel]","{'analyst_tools': ['excel'], 'libraries': ['gd...",112785.0
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"[mongodb, mongodb, python, r, sql, mysql, mari...","{'analyst_tools': ['tableau'], 'cloud': ['orac...",144200.0

In [5]:
df_salary[['salary_year_avg','salary_year_inflated']].head()

     salary_year_avg  salary_year_inflated
28          109500.0             112785.00
77          140000.0             144200.00
92          120000.0             123600.00
100         228222.0             235068.66
109          89000.0              91670.00

### Turn String to List applying function

In [20]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)
    else:
        return skill_list

In [ ]:
df_salary['job_skills'] = df_salary['job_skills'].apply(clean_list)

df_salary.head(2)

### Apply Function on rows

In [21]:
def projected_salary(row):
    if 'Senior' in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']

In [22]:
df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

df_salary.head(2)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,salary_year_inflated
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"[gdpr, excel]","{'analyst_tools': ['excel'], 'libraries': ['gd...",112785.0
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"[mongodb, mongodb, python, r, sql, mysql, mari...","{'analyst_tools': ['tableau'], 'cloud': ['orac...",144200.0

In [ ]:
df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated']].head()

### If a salary match or dismash will return a result of High/Low on a new column

In [ ]:
def salary_category(x):
    if x >= 5000:
        return "High"
    else:
        return "Low"

df["salary_category"] = df["salary_year_avg"].map(salary_category)